sudo: required

services:
  - docker

script:
  - docker build -t alexksak/fission-scrapy-env .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push alexksak/fission-scrapy-env
