sudo: required

services:
  - docker

deploy:
  provider: script
  on:
    branch: master
    tags: true
  script:
    - docker build -t alexksak/fission-scrapy-env:$(TRAVIS_TAG) .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push alexksak/fission-scrapy-env:$(TRAVIS_TAG)
